# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
  - id: 1
    start_block: 0
    contracts:
      - name: TetherToken
        address:
          - 0xdAC17F958D2ee523a2206206994597C13D831ec7
        handler: src/EventHandlers.ts
        events:
          - event: AddedBlackList(address _user)
          - event: DestroyedBlackFunds(address _blackListedUser, uint256 _balance)
          - event: RemovedBlackList(address _user)
      - name: FiatTokenProxy
        address:
          - 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
        handler: src/EventHandlers.ts
        events:
          - event: Blacklisted(address indexed _account)
          - event: UnBlacklisted(address indexed _account)
      - name: USD1
        address:
          - 0x3398385c205C060ef54744ee817c1487e28A6616
        handler: src/EventHandlers.ts
        events:
          - event: Freeze(address indexed caller, address indexed account)
          - event: Unfreeze(address indexed caller, address indexed account)
      - name: RLUSD
        address:
          - 0x8292bb45bf1ee4d140127049757c2e0ff06317ed
        handler: src/EventHandlers.ts
        events:
          - event: AccountPaused(address account)
          - event: AccountUnpaused(address account)
unordered_multichain_mode: true
preload_handlers: true
